In [2]:
import numpy as np
a = np.array(10)
print(a)
print(a.ndim)
print(a.shape)

10
0
()


In [5]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
print(arr.size)

int64
5


In [10]:
m = np.array([[1,2,3],[4,5,6]])
print(m)
print(m.ndim)
print(m.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [14]:
x=np.array(['1','2''3'])
print(x.dtype)

<U2


In [20]:
r=np.arange(0,10)
print(r)
print(r.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [23]:
r2 = np.arange(1,11,2)
r2

array([1, 3, 5, 7, 9])

In [28]:
m = np.arange(12).reshape(3,4)
print(m)
print(m.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [30]:
m2 = np.arange(12).reshape(4,3)
print(m2)
print(m2.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [34]:
r = np.array([[1,2],[3,4]])
result = r.flatten()
result

array([1, 2, 3, 4])

In [36]:
lin = np.linspace(0,1,5)
lin

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
a = np.arange(10)
print(a[0],a[-1],a[:3])

0 9 [0 1 2]


In [48]:
b = np.arange(12).reshape(3,4)
print(b)
print(b[0],b[:, -1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3] [ 3  7 11]


In [51]:
b = np.arange(12).reshape(3,4)
sub = b[1,0:2]
print(sub)

[4 5]


In [56]:
c = np.arange(25).reshape(5,5)
print(c)
diag = c[range(5), range(5)]
diag

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([ 0,  6, 12, 18, 24])

In [67]:
d = np.arange(0,12).reshape(4,3)
# d
d_tail= d[-2:]
d_tail

array([[ 6,  7,  8],
       [ 9, 10, 11]])